// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: authz_service/v1/subject.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveSubRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubId string                `protobuf:"bytes,1,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"`
	Roles []string              `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	Refs  []*SaveSubRequest_Ref `protobuf:"bytes,3,rep,name=refs,proto3" json:"refs,omitempty"`
}

func (x *SaveSubRequest) Reset() {
	*x = SaveSubRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authz_service_v1_subject_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveSubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSubRequest) ProtoMessage() {}

func (x *SaveSubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authz_service_v1_subject_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSubRequest.ProtoReflect.Descriptor instead.
func (*SaveSubRequest) Descriptor() ([]byte, []int) {
	return file_authz_service_v1_subject_proto_rawDescGZIP(), []int{0}
}

func (x *SaveSubRequest) GetSubId() string {
	if x != nil {
		return x.SubId
	}
	return ""
}

func (x *SaveSubRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *SaveSubRequest) GetRefs() []*SaveSubRequest_Ref {
	if x != nil {
		return x.Refs
	}
	return nil
}

type DeleteSubRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubId string `protobuf:"bytes,1,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"`
}

func (x *DeleteSubRequest) Reset() {
	*x = DeleteSubRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authz_service_v1_subject_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubRequest) ProtoMessage() {}

func (x *DeleteSubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authz_service_v1_subject_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubRequest) Descriptor() ([]byte, []int) {
	return file_authz_service_v1_subject_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteSubRequest) GetSubId() string {
	if x != nil {
		return x.SubId
	}
	return ""
}

type DeleteRefRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefId string `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
}

func (x *DeleteRefRequest) Reset() {
	*x = DeleteRefRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authz_service_v1_subject_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRefRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRefRequest) ProtoMessage() {}

func (x *DeleteRefRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authz_service_v1_subject_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRefRequest.ProtoReflect.Descriptor instead.
func (*DeleteRefRequest) Descriptor() ([]byte, []int) {
	return file_authz_service_v1_subject_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteRefRequest) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

type SubRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubId string `protobuf:"bytes,1,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"`
	RefId string `protobuf:"bytes,2,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
}

func (x *SubRequest) Reset() {
	*x = SubRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authz_service_v1_subject_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubRequest) ProtoMessage() {}

func (x *SubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authz_service_v1_subject_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubRequest.ProtoReflect.Descriptor instead.
func (*SubRequest) Descriptor() ([]byte, []int) {
	return file_authz_service_v1_subject_proto_rawDescGZIP(), []int{3}
}

func (x *SubRequest) GetSubId() string {
	if x != nil {
		return x.SubId
	}
	return ""
}

func (x *SubRequest) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

type SubResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubId string             `protobuf:"bytes,1,opt,name=sub_id,json=subId,proto3" json:"sub_id,omitempty"`
	Roles []string           `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	Refs  []*SubResponse_Ref `protobuf:"bytes,3,rep,name=refs,proto3" json:"refs,omitempty"`
}

func (x *SubResponse) Reset() {
	*x = SubResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authz_service_v1_subject_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubResponse) ProtoMessage() {}

func (x *SubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authz_service_v1_subject_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubResponse.ProtoReflect.Descriptor instead.
func (*SubResponse) Descriptor() ([]byte, []int) {
	return file_authz_service_v1_subject_proto_rawDescGZIP(), []int{4}
}

func (x *SubResponse) GetSubId() string {
	if x != nil {
		return x.SubId
	}
	return ""
}

func (x *SubResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *SubResponse) GetRefs() []*SubResponse_Ref {
	if x != nil {
		return x.Refs
	}
	return nil
}

type SaveSubRequest_Ref struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefId  string   `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	Roles  []string `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	Delete bool     `protobuf:"varint,3,opt,name=delete,proto3" json:"delete,omitempty"`
}

func (x *SaveSubRequest_Ref) Reset() {
	*x = SaveSubRequest_Ref{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authz_service_v1_subject_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveSubRequest_Ref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSubRequest_Ref) ProtoMessage() {}

func (x *SaveSubRequest_Ref) ProtoReflect() protoreflect.Message {
	mi := &file_authz_service_v1_subject_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSubRequest_Ref.ProtoReflect.Descriptor instead.
func (*SaveSubRequest_Ref) Descriptor() ([]byte, []int) {
	return file_authz_service_v1_subject_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SaveSubRequest_Ref) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

func (x *SaveSubRequest_Ref) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *SaveSubRequest_Ref) GetDelete() bool {
	if x != nil {
		return x.Delete
	}
	return false
}

type SubResponse_Ref struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefId string   `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	Roles []string `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *SubResponse_Ref) Reset() {
	*x = SubResponse_Ref{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authz_service_v1_subject_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubResponse_Ref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubResponse_Ref) ProtoMessage() {}

func (x *SubResponse_Ref) ProtoReflect() protoreflect.Message {
	mi := &file_authz_service_v1_subject_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubResponse_Ref.ProtoReflect.Descriptor instead.
func (*SubResponse_Ref) Descriptor() ([]byte, []int) {
	return file_authz_service_v1_subject_proto_rawDescGZIP(), []int{4, 0}
}

func (x *SubResponse_Ref) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

func (x *SubResponse_Ref) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_authz_service_v1_subject_proto protoreflect.FileDescriptor

var file_authz_service_v1_subject_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x76, 0x31, 0x2f, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbb, 0x01, 0x0a, 0x0e, 0x53, 0x61, 0x76, 0x65,
	0x53, 0x75, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x75,
	0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x75, 0x62, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x04, 0x72, 0x65, 0x66, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x61, 0x76, 0x65, 0x53, 0x75, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x52, 0x65, 0x66, 0x52, 0x04, 0x72, 0x65, 0x66, 0x73, 0x1a, 0x4a, 0x0a, 0x03, 0x52, 0x65, 0x66,
	0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x72, 0x65, 0x66, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x22, 0x29, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x75, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x75, 0x62,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x75, 0x62, 0x49, 0x64,
	0x22, 0x29, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x66, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x66, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x0a, 0x53,
	0x75, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x75, 0x62,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x75, 0x62, 0x49, 0x64,
	0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x72, 0x65, 0x66, 0x49, 0x64, 0x22, 0x9d, 0x01, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x75, 0x62, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x75, 0x62, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x72,
	0x6f, 0x6c, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x04, 0x72, 0x65, 0x66, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75,
	0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x66, 0x52, 0x04, 0x72,
	0x65, 0x66, 0x73, 0x1a, 0x32, 0x0a, 0x03, 0x52, 0x65, 0x66, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x65,
	0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x66, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x32, 0xff, 0x01, 0x0a, 0x07, 0x53, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x12, 0x3b, 0x0a, 0x07, 0x53, 0x61, 0x76, 0x65, 0x53, 0x75, 0x62, 0x12, 0x18,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x53, 0x75,
	0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x3f, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x75, 0x62, 0x12, 0x1a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x75, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x3f, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x66, 0x12, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x35, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x12, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75,
	0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x4a, 0x0a, 0x1b, 0x6f, 0x72, 0x67,
	0x2e, 0x66, 0x75, 0x6e, 0x63, 0x61, 0x72, 0x64, 0x73, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x42, 0x0c, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x76, 0x31, 0xaa,
	0x02, 0x13, 0x46, 0x75, 0x6e, 0x43, 0x61, 0x72, 0x64, 0x73, 0x4f, 0x72, 0x67, 0x2e, 0x47, 0x72,
	0x70, 0x63, 0x2e, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_authz_service_v1_subject_proto_rawDescOnce sync.Once
	file_authz_service_v1_subject_proto_rawDescData = file_authz_service_v1_subject_proto_rawDesc
)

func file_authz_service_v1_subject_proto_rawDescGZIP() []byte {
	file_authz_service_v1_subject_proto_rawDescOnce.Do(func() {
		file_authz_service_v1_subject_proto_rawDescData = protoimpl.X.CompressGZIP(file_authz_service_v1_subject_proto_rawDescData)
	})
	return file_authz_service_v1_subject_proto_rawDescData
}

var file_authz_service_v1_subject_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_authz_service_v1_subject_proto_goTypes = []interface{}{
	(*SaveSubRequest)(nil),     // 0: proto.v1.SaveSubRequest
	(*DeleteSubRequest)(nil),   // 1: proto.v1.DeleteSubRequest
	(*DeleteRefRequest)(nil),   // 2: proto.v1.DeleteRefRequest
	(*SubRequest)(nil),         // 3: proto.v1.SubRequest
	(*SubResponse)(nil),        // 4: proto.v1.SubResponse
	(*SaveSubRequest_Ref)(nil), // 5: proto.v1.SaveSubRequest.Ref
	(*SubResponse_Ref)(nil),    // 6: proto.v1.SubResponse.Ref
	(*emptypb.Empty)(nil),      // 7: google.protobuf.Empty
}
var file_authz_service_v1_subject_proto_depIdxs = []int32{
	5, // 0: proto.v1.SaveSubRequest.refs:type_name -> proto.v1.SaveSubRequest.Ref
	6, // 1: proto.v1.SubResponse.refs:type_name -> proto.v1.SubResponse.Ref
	0, // 2: proto.v1.Subject.SaveSub:input_type -> proto.v1.SaveSubRequest
	1, // 3: proto.v1.Subject.DeleteSub:input_type -> proto.v1.DeleteSubRequest
	2, // 4: proto.v1.Subject.DeleteRef:input_type -> proto.v1.DeleteRefRequest
	3, // 5: proto.v1.Subject.GetSub:input_type -> proto.v1.SubRequest
	7, // 6: proto.v1.Subject.SaveSub:output_type -> google.protobuf.Empty
	7, // 7: proto.v1.Subject.DeleteSub:output_type -> google.protobuf.Empty
	7, // 8: proto.v1.Subject.DeleteRef:output_type -> google.protobuf.Empty
	4, // 9: proto.v1.Subject.GetSub:output_type -> proto.v1.SubResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_authz_service_v1_subject_proto_init() }
func file_authz_service_v1_subject_proto_init() {
	if File_authz_service_v1_subject_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_authz_service_v1_subject_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveSubRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authz_service_v1_subject_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSubRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authz_service_v1_subject_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRefRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authz_service_v1_subject_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authz_service_v1_subject_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authz_service_v1_subject_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveSubRequest_Ref); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authz_service_v1_subject_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubResponse_Ref); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_authz_service_v1_subject_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authz_service_v1_subject_proto_goTypes,
		DependencyIndexes: file_authz_service_v1_subject_proto_depIdxs,
		MessageInfos:      file_authz_service_v1_subject_proto_msgTypes,
	}.Build()
	File_authz_service_v1_subject_proto = out.File
	file_authz_service_v1_subject_proto_rawDesc = nil
	file_authz_service_v1_subject_proto_goTypes = nil
	file_authz_service_v1_subject_proto_depIdxs = nil
}
